// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzbOiC4kKhwjdxNxuI692Q2mCyNYFA-DE',
    appId: '1:117197391096:web:8f810338bbc6c41bfe670d',
    messagingSenderId: '117197391096',
    projectId: 'flutter-app-project-519ee',
    authDomain: 'flutter-app-project-519ee.firebaseapp.com',
    storageBucket: 'flutter-app-project-519ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrJcIqtRi-7fg8hyLinltu3w8pTniiGds',
    appId: '1:117197391096:android:28581ec4a5bb08d0fe670d',
    messagingSenderId: '117197391096',
    projectId: 'flutter-app-project-519ee',
    storageBucket: 'flutter-app-project-519ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtYtVfMA_m_1s-PtzH-MZLSy14ObUKtMw',
    appId: '1:117197391096:ios:2dd3fc0c2d28d36afe670d',
    messagingSenderId: '117197391096',
    projectId: 'flutter-app-project-519ee',
    storageBucket: 'flutter-app-project-519ee.appspot.com',
    iosClientId: '117197391096-eqmag5dut4rlbped223rf50jop2o5enk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExerciseApp',
  );
}
